---
- block:

  - name: Local action | Create local temporary directory for certificates generation
    local_action:
      module: file
      path: "{{ local_certs_path }}"
      state: directory

  - name: Local action | Download certificates generation tool
    local_action:
      module: get_url
      url: "{{ certs_gen_tool_url }}"
      dest: "{{ local_certs_path }}/search-guard-tlstool-{{ certs_gen_tool_version }}.zip"

  - name: Local action | Extract the certificates generation tool
    local_action:
      module: unarchive
      src: "{{ local_certs_path }}/search-guard-tlstool-1.7.zip"
      dest: "{{ local_certs_path }}/"

  - name: Local action | Add the execution bit to the binary
    local_action:
      module: file
      dest: "{{ local_certs_path }}/tools/sgtlstool.sh"
      mode: a+x

  - name: Local action | Prepare the certificates generation template file
    local_action:
      module: template
      src: "templates/tlsconfig.yml.j2"
      dest: "{{ local_certs_path }}/config/tlsconfig.yml"


  - name: Create a directory if it does not exist
    file:
      path: "{{ local_certs_path }}/certs/"
      state: directory
      mode: '0755'
    delegate_to: localhost

  - name: Local action | Check if root CA file exists
    local_action:
      module: stat
      path: "{{ local_certs_path }}/certs/root-ca.key"
    register: root_ca_file

  - name: Local action | Generate the node & admin certificates in local
    local_action:
      module: command {{ local_certs_path }}/tools/sgtlstool.sh -c {{ local_certs_path }}/config/tlsconfig.yml -ca -crt -t {{ local_certs_path }}/certs/ -f -o
    when: not root_ca_file.stat.exists

  - name: Local action | Generate the node & admin certificates using an existing root CA
    local_action:
      module: command {{ local_certs_path }}/tools/sgtlstool.sh -c {{ local_certs_path }}/config/tlsconfig.yml -ca -crt -t {{ local_certs_path }}/certs/ -f
    when: root_ca_file.stat.exists
  run_once: true
  tags:
  - generate-certs