---
- include: RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: Debian.yml
  when: ansible_os_family == "Debian"

- include: config.yml
  when: logstash_create_config

- name: Ensure Logstash started and enabled
  service:
    name: logstash
    enabled: yes
    state: started

- include: "RMRedHat.yml"
  when: ansible_os_family == "RedHat"

- include: "RMDebian.yml"
  when: ansible_os_family == "Debian"
