---
- name: Debian/Ubuntu | Install apt-transport-https and ca-certificates
  apt:
    name: "{{ item }}"
    state: present
    cache_valid_time: 3600
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Debian/Ubuntu | Add Elasticsearch GPG key
  apt_key:
    keyserver: "{{ elasticrepo_gpg_keyserver }}"
    id: 46095ACC8548582C1A2699A9D27D666CD88E42B4

- name: Debian/Ubuntu | Install Elastic repo
  apt_repository:
    repo: "deb {{ elasticrepo_server }} stable main"
    state: present
    filename: 'elastic_repo'
    update_cache: yes

- name: Debian/Ubuntu | Install Kibana
  apt:
    name: "kibana={{ elastic_stack_version }}"
    state: present
    cache_valid_time: 3600
  tags: install
