---
# Single scenario: 1 manager + 2 agentless endpoints

dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint roles
  flake8 molecule
platforms:
  ################################################
  # Wazuh Managers
  ################################################
  - name: molecule_agentless_manager_centos7
    hostname: wazuh-mgr01
    image: geerlingguy/docker-centos7-ansible
    command: /sbin/init
    pre_build_image: true
    privileged: true
    memory_reservation: 512m
    memory: 1024m
    groups:
      - managers
    ulimits:
      - nofile:262144:262144
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  ################################################
  # Wazuh Agents
  ################################################
  - name: molecule_agentless_agent_centos7
    hostname: wazuh-agent01
    image: geerlingguy/docker-centos7-ansible
    command: /sbin/init
    pre_build_image: true
    privileged: true
    memory: 1024m
    memory_reservation: 512m
    groups:
      - agents
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  - name: molecule_agentless_agent_debian9
    hostname: wazuh-agent02
    image: geerlingguy/docker-debian9-ansible
    command: /sbin/init
    pre_build_image: true
    privileged: true
    memory: 1024m
    memory_reservation: 512m
    groups:
      - agents
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  ansible_args:
    - -vv
  inventory:
    links:
      group_vars: group_vars
  playbooks:
    create: create.yml
    converge: converge.yml
    prepare: prepare.yml
  env:
    ANSIBLE_ROLES_PATH: ./roles
  lint:
    name: ansible-lint
    enabled: false
scenario:
  name: single-wazuh-agentless
  test_sequence:
    - dependency
    - syntax
    - create
    - prepare
    - converge
    #- idempotence
    - verify
    - cleanup
    - destroy
verifier:
  name: testinfra