---
- import_tasks: RedHat.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: Debian.yml
  when: ansible_os_family == 'Debian'

- name: Make sure Elasticsearch is running before proceeding.
  wait_for: host={{ elasticsearch_network_host }} port={{ elasticsearch_http_port }} delay=3 timeout=300
  tags: configure

- name: Kibana configuration
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: root
    group: root
    mode: 0664
  notify: restart kibana
  tags: configure

- name: Checking Wazuh-APP version
  shell: "grep -c -E 'version.*{{ elastic_stack_version }}' /usr/share/kibana/plugins/wazuh/package.json | xargs echo"
  args:
    removes: /usr/share/kibana/plugins/wazuh/package.json
  register: wazuh_app_verify
  tags: install

- name: Upgrading Wazuh-APP
  shell: "{{ item }}"
  when: wazuh_app_verify.stdout == "0"
  with_items:
    - /usr/share/kibana/bin/kibana-plugin remove wazuh
    - rm -rf /usr/share/kibana/optimize/bundles
  tags: install

- name: Install Wazuh-APP (can take a while)
  shell: "/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-2.1.1_{{ elastic_stack_version }}.zip"
  args:
    creates: /usr/share/kibana/plugins/wazuh/package.json
  notify: restart kibana
  tags: install

- name: Ensure Kibana started and enabled
  service:
    name: kibana
    enabled: yes
    state: started

- import_tasks: RMRedHat.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: RMDebian.yml
  when: ansible_os_family == 'Debian'
