---
- name: RedHat/CentOS/Fedora | Add Elasticsearch GPG key
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: RedHat/CentOS/Fedora | Install Elastic repo
  yum_repository:
    name: elk_repo
    description: Elastic repository for 5.x packages
    baseurl: https://artifacts.elastic.co/packages/5.x/yum
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    gpgcheck: yes

- name: RedHat/CentOS/Fedora | Install Kibana
  package: name=kibana-{{ elastic_stack_version }} state=present
  tags: install
