---
  - name: Install Wazuh Agent from .deb packages
    apt:
      deb: "{{ wazuh_custom_packages_installation_agent_deb_url }}"
      state: present
    when:
      - ansible_os_family|lower == "debian"
      - wazuh_custom_packages_installation_agent_enabled

  - name: Install Wazuh Agent from .rpm packages
    yum:
      name: "{{ wazuh_custom_packages_installation_agent_rpm_url }}"
      state: present
    when:
      - ansible_os_family|lower == "redhat"
      - wazuh_custom_packages_installation_agent_enabled