---

elasticsearch_http_port: 9200
elasticsearch_network_host: 127.0.0.1
elasticsearch_reachable_host: 127.0.0.1
elasticsearch_jvm_xms: null
elastic_stack_version: 7.9.3
elasticsearch_lower_disk_requirements: false
elasticsearch_path_repo: []

elasticrepo:
  apt: 'https://artifacts.elastic.co/packages/7.x/apt'
  yum: 'https://artifacts.elastic.co/packages/7.x/yum'
  gpg: 'https://artifacts.elastic.co/GPG-KEY-elasticsearch'
  key_id: '46095ACC8548582C1A2699A9D27D666CD88E42B4'

# Cluster Settings
single_node: true
elasticsearch_cluster_name: wazuh
elasticsearch_node_name: node-1
elasticsearch_bootstrap_node: false
elasticsearch_node_master: false
elasticsearch_cluster_nodes:
  - 127.0.0.1
elasticsearch_discovery_nodes:
  - 127.0.0.1
elasticsearch_node_data: true
elasticsearch_node_ingest: true

# X-Pack Security
elasticsearch_xpack_security: false
elasticsearch_xpack_security_password: elastic_pass


#####################################
# SSL for Elasticsearch security
#
# These variables are shared between elasticsearch and OpenDistro role.
# Eventually they will be moved to their own independant role so they
# can be reused for both elasticsearch and opendistro deployments.
#
# elasticsearch_ssl_method can be one of these:
#
# * legacy: use certutil method invoking elasticsearch-certutil on bootstrap elastic node.
#             deprecated, as it requires two stages to avoid overwriting certs.
#
# * ansible: newer method for generating certificate chain with ansible, it's idempotent
#            so it doesn't require multiple runs of the role.
#

elasticsearch_ssl_method: legacy

node_certs_generator: false
node_certs_source: /usr/share/elasticsearch
node_certs_destination: /etc/elasticsearch/certs

#####################################
# SSL Method: legacy

# This uses the distributed tool certutil:
# * https://www.elastic.co/guide/en/elasticsearch/reference/current/certutil.html

master_certs_path: "{{ playbook_dir }}/es_certs"
generate_CA: true
ca_key_name: ""
ca_cert_name: ""
ca_password: ""

#####################################
# SSL Method: ansible

# General settings
elasticsearch_ssl_cert_dir: '{{ playbook_dir }}/es_certs'
elasticsearch_ssl_cert_backend: cryptography
elasticsearch_ssl_cert_delegate: localhost
elasticsearch_ssl_cert_become: no

# If hosts already has certificates in destination folder, skip all cert tasks
elasticsearch_ssl_cert_skip_deployed: yes

# CA settings
elasticsearch_ssl_ca_dir: '{{ elasticsearch_ssl_cert_dir }}/ca'
elasticsearch_ssl_ca_cn: Wazuh Autogenerated CA
elasticsearch_ssl_ca_name: ca
elasticsearch_ssl_ca_type: RSA
elasticsearch_ssl_ca_size: 2048
elasticsearch_ssl_ca_backup: yes
elasticsearch_ssl_ca_force: no
#elasticsearch_ssl_ca_pass: ''

# TrustAnchors is needed for Java, for details see JDK-8230318:
#  * https://www.oracle.com/java/technologies/javase/8u241-relnotes.html

elasticsearch_ssl_ca_constraints:
  - 'CA:TRUE'

# Hosts certificate defaults
elasticsearch_ssl_default_type: RSA
elasticsearch_ssl_default_size: 2048
elasticsearch_ssl_default_backup: yes
elasticsearch_ssl_default_regenerate: no
elasticsearch_ssl_default_constraints:
  - 'CA:FALSE'