---
- name: Copy Filebeat configuration.
  template:
    src: filebeat.yml.j2
    dest: "/etc/filebeat/filebeat.yml"
    owner: root
    group: root
    mode: 0400
  notify: restart filebeat
  tags: configure

- name: Copy Elasticsearch template.
  template:
    src: elasticsearch.yml.j2
    dest: "/etc/filebeat/wazuh-template.json"
    owner: root
    group: root
    mode: 0400
  notify: restart filebeat
  tags: configure