---
- name: Debian/Ubuntu | Install apt-transport-https and ca-certificates
  apt:
    name: "{{ item }}"
    state: present
    cache_valid_time: 3600
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Debian/Ubuntu | Add Elasticsearch apt key.
  apt_key:
    keyserver: "{{ elasticrepo_gpg_keyserver }}"
    id: 46095ACC8548582C1A2699A9D27D666CD88E42B4

- name: Debian/Ubuntu | Add Filebeat repository.
  apt_repository:
    repo: "deb {{ elasticrepo_server }} stable main"
    state: present
    update_cache: yes
