---
- import_tasks: RedHat.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: Debian.yml
  when: ansible_os_family == 'Debian'

- name: CentOS/RedHat |  Install Filebeat.
  package: name=filebeat-{{ filebeat_version }} state=present
  register: filebeat_installing_package
  until: filebeat_installing_package is succeeded
  when:
    - ansible_distribution in ['CentOS','RedHat']
  tags:
    - install

- name: Debian/Ubuntu | Install Filebeat.
  apt:
    name: filebeat={{ filebeat_version }}
    state: present
    cache_valid_time: 3600
  register: filebeat_installing_package_debian
  until: filebeat_installing_package_debian is succeeded
  when:
    - not (ansible_distribution in ['CentOS','RedHat'])
  tags:
    - init

- name: Copying node's certificate from master
  copy:
    src: "{{item}}"
    dest: "{{node_certs_destination}}/"
  with_items: 
    - "{{master_certs_destination}}/{{filebeat_node_name}}/{{ filebeat_node_name }}.key" 
    - "{{master_certs_destination}}/{{filebeat_node_name}}/{{ filebeat_node_name }}.crt"
    - "{{master_certs_destination}}/ca/ca.crt"
  tags: xpack-security

- name: Ensuring certificates folder owner
  file:
    path: "{{ node_certs_destination }}/"
    mode: '0770'
    recurse: yes
  when:
    - filebeat_xpack_security
  tags: xpack-security

- import_tasks: config.yml
  when: filebeat_create_config
  notify: restart filebeat

- name: Reload systemd
  systemd: daemon_reload=yes
  ignore_errors: true
  when:
    - not (ansible_distribution == "Amazon" and ansible_distribution_major_version == "NA")
    - not (ansible_distribution == "Ubuntu" and ansible_distribution_version is version('15.04', '<'))
    - not (ansible_distribution == "Debian" and ansible_distribution_version is version('8', '<'))
    - not (ansible_os_family == "RedHat" and ansible_distribution_version is version('7', '<'))

- name: Ensure Filebeat is started and enabled at boot.
  service:
    name: filebeat
    state: started
    enabled: true

- import_tasks: "RMRedHat.yml"
  when: ansible_os_family == "RedHat"

- import_tasks: "RMDebian.yml"
  when: ansible_os_family == "Debian"
