---
- name: RedHat/CentOS/Fedora/Amazon Linux | Install Filebeats repo
  yum_repository:
    name: elastic_repo
    description: Elastic repository for 7.x packages
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    gpgcheck: yes
