---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Filebeat.
  package: name=filebeat state=present

- include: config.yml
  when: filebeat_create_config

- name: Ensure Filebeat is started and enabled at boot.
  service:
    name: filebeat
    state: started
    enabled: yes

- name: Remove the correct repository
  include: "RMRedHat.yml"
  when: ansible_os_family == "RedHat"

- name: Remove the correct repository
  include: "RMDebian.yml"
  when: ansible_os_family == "Debian"
