---
- name: RedHat/CentOS/Fedora | Install Filebeats repo
  yum_repository:
    name: elastic_repo
    description: Elastic repository for 5.x packages
    baseurl: https://artifacts.elastic.co/packages/5.x/yum
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    gpgcheck: yes
