---
- name: Debian/Ubuntu | Install apt-transport-https and ca-certificates
  apt: name="{{ item }}" state=present update_cache=yes
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Debian/Ubuntu | Installing repository keyyyy
  shell: curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | apt-key add -

- name: Debian/Ubuntu | Add Wazuh repositories
  apt_repository:
    repo: deb https://packages.wazuh.com/apt {{ ansible_distribution_release }} main
    state: present
    update_cache: yes

- name: Set Distribution CIS filename for debian
  set_fact:
    cis_distribution_filename: cis_debian_linux_rcl.txt
  when: ansible_os_family == "Debian"
