---
- name: RedHat | download Oracle Java RPM
  get_url:
    url: http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.rpm
    dest: /tmp/jdk-8-linux-x64.rpm
    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
  register: oracle_java_task_rpm_download
  become: yes

- name: RedHat | Install Oracle Java RPM
  action: "yum name=/tmp/jdk-8-linux-x64.rpm state=present"
  when: not oracle_java_task_rpm_download|skipped
  become: yes
  tags: install

- name: RedHat | Add Elasticsearch GPG key
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: RedHat | Install Elastic repo
  yum_repository:
    name: elk_repo
    description: Elastic repository for 5.x packages
    baseurl: https://artifacts.elastic.co/packages/5.x/yum
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    gpgcheck: yes

- name: RedHat | Install Elasticsarch
  yum: pkg=elasticsearch-{{ elk_stack_version }} state=present
  tags: install
