---
- name: Debian/Ubuntu | Install apt-transport-https and ca-certificates
  apt:
    name: "{{ item }}"
    state: present
    cache_valid_time: 3600
  with_items:
    - apt-transport-https
    - ca-certificates

- when: elasticsearch_install_java
  block:
    - name: Debian/Ubuntu | Setting webupd8 repository
      apt_repository:
        repo: 'ppa:webupd8team/java'
        codename: 'xenial'
        update_cache: yes

    - name: Debian/Ubuntu | Accept Oracle Java 8 license
      debconf:
        name: oracle-java8-installer
        question: shared/accepted-oracle-license-v1-1
        value: true
        vtype: boolean

    - name: Debian/Ubuntu | Oracle Java 8 installer
      apt:
        name: oracle-java8-installer
        state: present
        cache_valid_time: 3600
      tags: install

- name: Debian/Ubuntu | Add Elasticsearch GPG key.
  apt_key:
    keyserver: "{{ elasticrepo_gpg_keyserver }}"
    id: 46095ACC8548582C1A2699A9D27D666CD88E42B4

- name: Debian/Ubuntu | Install Elastic repo
  apt_repository:
    repo: "deb {{ elasticrepo_server }} stable main"
    state: present
    filename: 'elastic_repo'
    update_cache: yes

- name: Debian/Ubuntu | Install Elasticsarch
  apt:
    name: "elasticsearch={{ elastic_stack_version }}"
    state: present
    cache_valid_time: 3600
  tags: install
