---
- name: Debian/Ubuntu | Install apt-transport-https and ca-certificates
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present
  register: elasticsearch_ca_packages_installed
  until: elasticsearch_ca_packages_installed is succeeded

- name: "Install Java Repo for Trusty"
  apt_repository: repo='ppa:openjdk-r/ppa'
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version | int == 14

- when: elasticsearch_install_java
  block:
    - name: Debian/Ubuntu | Install OpenJDK 1.8
      apt: name=openjdk-8-jre state=present cache_valid_time=3600
      register: elasticsearch_jre_packages_installed
      until: elasticsearch_jre_packages_installed is succeeded
      tags: install

- name: Debian/Ubuntu | Add Elasticsearch GPG key.
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present

- name: Debian/Ubuntu | Install Elastic repo
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/6.x/apt stable main'
    state: present
    filename: 'elastic_repo'
    update_cache: true

- name: Debian/Ubuntu | Install Elasticsarch
  apt:
    name: "elasticsearch={{ elastic_stack_version }}"
    state: present
    cache_valid_time: 3600
  register: elasticsearch_main_packages_installed
  until: elasticsearch_main_packages_installed is succeeded
  tags: install
