---

- name: RedHat/CentOS/Fedora | Install Elastic repo
  yum_repository:
    name: elastic_repo
    description: Elastic repository for 7.x packages
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    gpgcheck: true
  changed_when: false

- name: CentOS x.x => x.x < 7.0 | Installing Java
  yum:
    name: java-1.8.0-openjdk.x86_64
    state: present
  when:
    - ansible_distribution in ['CentOS', 'RedHat'] and ansible_distribution_major_version|int < 7

- name: RedHat/CentOS/Fedora | Install Elasticsarch
  package: name=elasticsearch-{{ elastic_stack_version }} state=present
  tags: install
