---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  enabled: false
platforms:

  - name: manager_centos7
    image: milcom/centos7-systemd
    command: /sbin/init
    ulimits:
      - nofile:262144:262144
    privileged: true
    memory_reservation: 2048m

  - name: ubuntu20
    image: jrei/systemd-ubuntu:20.04
    privileged: true

  - name: debian9
    image: jrei/systemd-debian:9
    privileged: true

provisioner:
  name: ansible
  config_options:
    defaults:
      hash_behaviour: merge
  env:
    ANSIBLE_ROLES_PATH: ./roles
  lint:
    name: ansible-lint
    enabled: false
scenario:
  name: default
  test_sequence:
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
    enabled: false
