---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  enabled: false # fix in seperate PR
platforms:
  - name: wazuh_manager_bionic
    image: ubuntu:bionic
  - name: wazuh_manager_xenial
    image: solita/ubuntu-systemd:xenial
    privileged: True
    command: /sbin/init
  - name: wazuh_manager_trusty
    image: ubuntu:trusty
  - name: wazuh_manager_centos6
    image: centos:6
  - name: wazuh_manager_centos7
    image: milcom/centos7-systemd
    privileged: True
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles
  lint:
    name: ansible-lint
    enabled: true # fix in seperate PR
scenario:
  name: default
  test_sequence:
    - lint
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
    enabled: true
