---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  enabled: false
platforms:
  - name: ubuntu2004
    image: ubuntu:20.04
  - name: debian10
    image: debian:10
  - name: amazonlinux
    image: amazonlinux
  - name: manager_centos7
    image: milcom/centos7-systemd
    command: /sbin/init
    ulimits:
      - nofile:262144:262144
    privileged: true
    memory_reservation: 2048m
provisioner:
  name: ansible
  config_options:
    defaults:
      hash_behaviour: merge
  env:
    ANSIBLE_ROLES_PATH: ./roles
  lint:
    name: ansible-lint
    enabled: false
scenario:
  name: default
  test_sequence:
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
    enabled: false
