---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-data:
      ignore: .virtualenv
platforms:
  #- name: bionic
  #  image: solita/ubuntu-systemd:bionic
  #  command: /sbin/init
  #  ulimits:
  #    - nofile:262144:262144
  #  privileged: true
  #  memory_reservation: 2048m
  #- name: xenial
  #  image: solita/ubuntu-systemd:xenial
  #  privileged: true
  #  memory_reservation: 2048m
  #  command: /sbin/init
  #  ulimits:
  #    - nofile:262144:262144
  #- name: trusty
  #image: ubuntu:trusty
  #privileged: true
  #memory_reservation: 2048m
  #ulimits:
      #- nofile:262144:262144
  #- name: centos6
  #  image: centos:6
  #  privileged: true
  #  memory_reservation: 2048m
  #  ulimits:
  #    - nofile:262144:262144
  - name: centos7
    image: milcom/centos7-systemd
    memory_reservation: 2048m
    privileged: true
    ulimits:
      - nofile:262144:262144
provisioner:
  name: ansible
  playbooks:
    docker:
      create: ../default/create.yml
      destroy: ../default/destroy.yml
      prepare: ../default/prepare.yml
  env:
    ANSIBLE_ROLES_PATH: ../../roles
  lint:
    name: ansible-lint
    enabled: true
  inventory:
    group_vars:
      all:
        elasticsearch_jvm_xms: 512
verifier:
  name: testinfra
  lint:
    name: flake8
