---
- name: Debian/Ubuntu | Install apt-transport-https and ca-certificates
  apt: name="{{ item }}" state=present update_cache=yes
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Debian/Ubuntu | Installing Wazuh repository key
  apt_key: url=https://packages.wazuh.com/key/GPG-KEY-WAZUH

- name: Debian/Ubuntu | Add Wazuh repositories
  apt_repository:
    repo: deb https://packages.wazuh.com/apt {{ ansible_distribution_release }} main
    state: present
    update_cache: yes

- name: Debian/Ubuntu | Installing NodeJS repository key
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Debian/Ubuntu | Add NodeSource repositories for Node.js
  apt_repository:
    repo: deb https://deb.nodesource.com/node_6.x {{ ansible_distribution_release }} main
    state: present
    update_cache: yes

- name: Debian/Ubuntu | Set Distribution CIS filename for Debian/Ubuntu
  set_fact:
    cis_distribution_filename: cis_debian_linux_rcl.txt

- name: Debian/Ubuntu | Install OpenScap
  package: name={{ item }} state=present
  with_items:
    - libopenscap8
    - xsltproc
  tags:
    - init
