---
- name: RedHat/CentOS | Install Nodejs repo
  yum_repository:
    name: NodeJS
    description: NodeJS-$releasever
    baseurl: https://rpm.nodesource.com/pub_6.x/el/$releasever/x86_64
    gpgkey: https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL
    gpgcheck: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: Fedora | Install Nodejs repo
  yum_repository:
    name: NodeJS
    description: NodeJS-$releasever
    baseurl: https://rpm.nodesource.com/pub_6.x/fc/$releasever/x86_64
    gpgkey: https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL
    gpgcheck: yes
  when: ansible_distribution == 'Fedora'

- name: CentOS | Install Wazuh repo
  yum_repository:
    name: wazuh_repo
    description: CentOS-$releasever - Wazuh
    baseurl: https://packages.wazuh.com/yum/el/$releasever/$basearch
    gpgkey: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    gpgcheck: yes
  when: ansible_distribution == 'CentOS'

- name: Fedora | Install Wazuh repo
  yum_repository:
    name: wazuh_repo
    description: Fedora-$releasever - Wazuh
    baseurl: https://packages.wazuh.com/yum/fc/$releasever/$basearch
    gpgkey: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    gpgcheck: yes
  when: ansible_distribution == 'Fedora'

- name: RedHat | Install Wazuh repo
  yum_repository:
    name: wazuh_repo
    description: CentOS-$releasever - Wazuh
    baseurl: https://packages.wazuh.com/yum/rhel/$releasever/$basearch
    gpgkey: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    gpgcheck: yes
  when: ansible_distribution == 'RedHat'

- name: RedHat/CentOS/Fedora | Install openscap
  package: name=openscap-scanner state=present
  tags:
    - init

- name: Set Distribution CIS filename for RHEL5/CentOS-5
  set_fact:
    cis_distribution_filename: cis_rhel5_linux_rcl.txt
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "5"

- name: Set Distribution CIS filename for RHEL6/CentOS-6
  set_fact:
    cis_distribution_filename: cis_rhel6_linux_rcl.txt
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

- name: Set Distribution CIS filename for RHEL7/CentOS-7
  set_fact:
    cis_distribution_filename: cis_rhel7_linux_rcl.txt
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
