---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-data:
      ignore: .virtualenv
platforms:
  - name: kibana_bionic
    image: solita/ubuntu-systemd:bionic
    command: /sbin/init
    ulimits:
      - nofile:262144:262144
    privileged: true
    memory_reservation: 1024m
  - name: kibana_xenial
    image: solita/ubuntu-systemd:xenial
    privileged: true
    memory_reservation: 1024m
    command: /sbin/init
    ulimits:
      - nofile:262144:262144
#  - name: trusty
#    image: ubuntu:trusty
#    memory_reservation: 1024m
#    ulimits:
#      - nofile:262144:262144
#  - name: centos6
#    image: centos:6
#    privileged: true
#    memory_reservation: 1024m
#    ulimits:
#      - nofile:262144:262144
  - name: kibana_centos7
    image: milcom/centos7-systemd
    memory_reservation: 1024m
    privileged: true
    ulimits:
      - nofile:262144:262144
provisioner:
  name: ansible
  config_options:
    defaults:
      hash_behaviour: merge
  playbooks:
    docker:
      create: ../default/create.yml
      destroy: ../default/destroy.yml
  env:
    ANSIBLE_ROLES_PATH: ../../roles
  lint:
    name: ansible-lint
    enabled: true
  inventory:
    group_vars:
      all:
        elasticsearch_jvm_xms: 256
verifier:
  name: testinfra
  lint:
    name: flake8
