---
elasticsearch_http_port: "9200"
elasticsearch_network_host: "127.0.0.1"
kibana_server_host: "0.0.0.0"
kibana_server_port: "5601"
elastic_stack_version: 6.5.4
wazuh_version: 3.8.0
elasticrepo_gpg_keyserver: pool.sks-keyservers.net
elasticrepo_server: https://artifacts.elastic.co/packages/6.x/apt
