---
- hosts: <your server host>
  roles:
      - {role: ../roles/wazuh/ansible-wazuh-manager}
      - {role: ../roles/elastic-stack/ansible-elasticsearch, elasticsearch_network_host: '0.0.0.0', single_node: true}
      - { role: ../roles/elastic-stack/ansible-kibana, elasticsearch_network_host: 'localhost' }
