---
- hosts: 172.16.0.161
  roles:
    - role: ../roles/wazuh/ansible-wazuh-manager
    - role: ../roles/wazuh/ansible-filebeat
      filebeat_output_elasticsearch_hosts: 172.16.0.161:9200
      filebeat_xpack_security: true
      filebeat_node_name: node-1
      node_certs_generator: true

