---
# The OpenDistro version
opendistro_version: 1.6.0

# The OpenDistro package repository
package_repos:
  yum: 
    opendistro: 
      baseurl: 'https://d3g5vo6xdbdb9a.cloudfront.net/yum/noarch/'
      gpg: 'https://d3g5vo6xdbdb9a.cloudfront.net/GPG-KEY-opendistroforelasticsearch'
    elasticsearch_oss:
      baseurl: 'https://artifacts.elastic.co/packages/oss-7.x/yum'
      gpg: 'https://artifacts.elastic.co/GPG-KEY-elasticsearch'

# Security password
opendistro_security_password: admin

# Set JVM memory limits
elasticsearch_jvm_xms: null