
name: Molecule tests for Wazuh Ansible

on: [push]

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Default scenario
      uses: './.github/actions/default'
