---
# Tasks specific for RedHat systems

- name: RedHat | Set some facts
  set_fact:
    ansible_distribution: centos
  when: ansible_distribution == "RedHat"

- name: RedHat | Install Wazuh repo
  yum_repository:
    name: NodeJS
    description: NodeJS-$releasever
    baseurl: https://rpm.nodesource.com/pub_6.x/el/$releasever/x86_64
    gpgkey: https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL
    gpgcheck: yes

- name: RedHat | Install NodeJS repo
  yum_repository:
    name: wazuh_repo
    description: CentOS-$releasever - Wazuh
    baseurl: https://packages.wazuh.com/yum/el/$releasever/$basearch
    gpgkey: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    gpgcheck: yes

- name: RedHat | Install epel repo
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ansible_distribution_major_version}}.noarch.rpm state=present

- name: RedHat | Install Wazuh Manager and Wazuh Api
  yum: pkg={{ item }}
       state=present
  with_items:
    - wazuh-manager
    - wazuh-api
  tags:
    - init

- name: RedHat | Install openscap
  yum: pkg=openscap-scanner
       state=present
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= 6
  tags:
    - init

- name: Set Distribution CIS filename for RHEL5
  set_fact:
    cis_distribution_filename: cis_rhel5_linux_rcl.txt
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "5"

- name: Set Distribution CIS filename for RHEL6
  set_fact:
    cis_distribution_filename: cis_rhel6_linux_rcl.txt
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

- name: Set Distribution CIS filename for RHEL7
  set_fact:
    cis_distribution_filename: cis_rhel7_linux_rcl.txt
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: Set ossec deploy facts for RedHat
  set_fact:
    ossec_server_config_filename: ossec-server.conf
    ossec_init_name: wazuh-manager
  when: ansible_os_family == "RedHat"
