---
# Remove repositories
- name: Remove NodeJS repository (and clean up left-over metadata)
  yum_repository:
    name: NodeJS
    state: absent


- name: Remove Wazuh repository (and clean up left-over metadata)
  yum_repository:
    name: wazuh_repo
    state: absent
